Feature: GastosFeature



  Como usuario del sistema
  Quiero poder registrar gastos
  Para gestionar los gastos de la empresa

Background:
  Given el usuario ingresa al ambiente 'http://localhost:31096/'
  When el usuario inicia sesión con usuario 'admin@plazafer.com' y contraseña 'calidad'
  And accede al módulo 'Gastos'
  And accede al submoudo 'Ver'
  And accede al submódulo 'NUEVO GASTO'

@RegistrarGasto
Scenario Outline: Registro de nuevo gasto - Casos variados
  When ingresa el documento '<documento>'
  And ingresa la fecha de gasto '<fecha_gasto>'
  And ingresa observaciones '<observaciones>'
  And ingresa el detalle '<detalle>'
  And ingresa el concepto '<concepto>'
  And ingresa el importe '<importe>'
  And selecciona el tipo de gasto '<gasto_al_credito>'
  And para gastos al crédito configurable ingresa inicial '<inicial>' cuotas '<cuotas>' y dia de pago '<dia_pago>'
  And <manejo_igv>
  Then <resultado_esperado>

    Examples:
      | caso_numero | documento   | fecha_gasto | observaciones     | detalle                         | concepto  | importe | gasto_al_credito           | inicial | cuotas | dia_pago | manejo_igv | resultado_esperado                                 |
      | 1           | 00000000    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | con_igv    | el gasto se registra exitosamente                  |
      | 2           | 00000000    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | con_igv    | el gasto se registra exitosamente                  |
      | 3           | 00000000    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | el gasto se registra exitosamente               |
      | 4           | 00000000    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | el gasto se registra exitosamente               |
      | 5           | 00000000    | 30/10/2025  |                   | Compra de materiales de oficina | DESCUENTO | 0       | gasto al credito rapido    |         |        |          | con_igv    | es necesario que el importe sea mayor a 0          |
      | 6           | 00000000    | 30/10/2025  |                   | Compra de materiales de oficina | DESCUENTO | 0       | gasto al credito rapido    |         |        |          | con_igv    | es necesario que el importe sea mayor a 0          |
      | 7           | 00000000    | 30/10/2025  |                   |                                 | DESCUENTO | 0       | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario que el importe sea mayor a 0       |
      | 8           | 00000000    | 30/10/2025  |                   |                                 | DESCUENTO | 0       | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario que el importe sea mayor a 0           |
      | 9           | 00000000    |             | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 10          | 00000000    |             | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 11          | 00000000    |             | Compra de insumos |                                 | DESCUENTO | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 12          | 00000000    |             | Compra de insumos |                                 | DESCUENTO | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 13          | 00000000    |             |                   | Compra de materiales de oficina | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 14          | 00000000    |             |                   | Compra de materiales de oficina | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 15          | 00000000    |             |                   |                                 | DESCUENTO | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 16          | 00000000    |             |                   |                                 | DESCUENTO | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 17          | 00000000    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | el gasto se registra exitosamente                       |
      | 18          | 00000000    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | el gasto se registra exitosamente                       |
      | 19          | 00000000    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | el gasto se registra exitosamente                       |
      | 20          | 00000000    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | el gasto se registra exitosamente                       |
      | 21          | 00000000    | 30/10/2025  |                   | Compra de materiales de oficina | DESCUENTO | 0       | sin gasto al credito       |         |        |          | con_igv    | es necesario que el importe sea mayor a 0           |
      | 22          | 00000000    | 30/10/2025  |                   | Compra de materiales de oficina | DESCUENTO | 0       | sin gasto al credito       |         |        |          | con_igv    | es necesario que el importe sea mayor a 0          |
      | 23          | 00000000    | 30/10/2025  |                   |                                 | DESCUENTO | 0       | sin gasto al credito       |         |        |          | con_igv    | es necesario que el importe sea mayor a 0           |
      | 24          | 00000000    | 30/10/2025  |                   |                                 | DESCUENTO | 0       | sin gasto al credito       |         |        |          | con_igv    | es necesario que el importe sea mayor a 0           |
      | 25          | 00000000    |             | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 26          | 00000000    |             | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 27          | 00000000    |             | Compra de insumos |                                 | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 28          | 00000000    |             | Compra de insumos |                                 | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 29          | 00000000    |             |                   | Compra de materiales de oficina | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 30          | 00000000    |             |                   | Compra de materiales de oficina | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 31          | 00000000    |             |                   |                                 | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 32          | 00000000    |             |                   |                                 | DESCUENTO | 110     | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 33          | 77541694    | 30/10/2025  |                   |                                 | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | sin_igv    | el gasto se registra exitosamente                       |
      | 34          | 77541694    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | sin_igv    | el gasto se registra exitosamente                       |
      | 35          | 77541694    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | sin_igv    | el gasto se registra exitosamente                       |
      | 36          | 77541694    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | gasto al credito rapido    |         |        |          | sin_igv    | el gasto se registra exitosamente                       |
      | 37          | 77541694    | 30/10/2025  |                   | Compra de materiales de oficina | DESCUENTO | 0       | gasto al credito rapido    |         |        |          | sin_igv    | es necesario que el importe sea mayor a 0          |
      | 38          | 77541694    | 30/10/2025  |                   | Compra de materiales de oficina | DESCUENTO | 0       | gasto al credito rapido    |         |        |          | sin_igv    | es necesario que el importe sea mayor a 0         |
      | 39          | 77541694    | 30/10/2025  |                   |                                 | DESCUENTO | 0       | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario que el importe sea mayor a 0          |
      | 40          | 77541694    | 30/10/2025  |                   |                                 | DESCUENTO | 0       | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario que el importe sea mayor a 0         |
      | 41          | 77541694    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | el gasto se registra exitosamente                       |
      | 42          | 77541694    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | DESCUENTO | 110     | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | el gasto se registra exitosamente                       |
      | 43          | 77541694    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | sin gasto al credito       |         |        |          | sin_igv    | el gasto se registra exitosamente                       |
      | 44          | 77541694    | 30/10/2025  | Compra de insumos |                                 | DESCUENTO | 110     | sin gasto al credito       |         |        |          | sin_igv    | el gasto se registra exitosamente                       |
      | 45          | 77541694    | 30/10/2025  |                   | Compra de materiales de oficina | DESCUENTO | 0       | sin gasto al credito       |         |        |          | sin_igv    | es necesario que el importe sea mayor a 0           |
      | 46          | 77541694    | 30/10/2025  |                   | Compra de materiales de oficina | DESCUENTO | 0       | sin gasto al credito       |         |        |          | sin_igv    | es necesario que el importe sea mayor a 0           |
      | 47          | 77541694    | 30/10/2025  |                   |                                 | DESCUENTO | 0       | sin gasto al credito       |         |        |          | sin_igv    | es necesario que el importe sea mayor a 0           |
      | 48          | 77541694    | 30/10/2025  |                   |                                 | DESCUENTO | 0       | sin gasto al credito       |         |        |          | sin_igv    | es necesario que el importe sea mayor a 0          |
      | 49          | 77541694    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito rapido    |         |        |          | sin_igv    | es necesario agregar un concepto                        |
      | 50          | 77541694    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito rapido    |         |        |          | sin_igv    | es necesario agregar un concepto                        |
      | 51          | 77541694    | 30/10/2025  | Compra de insumos |                                 | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario agregar un concepto                        |
      | 52          | 77541694    | 30/10/2025  | Compra de insumos |                                 | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario agregar un concepto                        |
      | 53          | 77541694    | 30/10/2025  |                   | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario agregar un concepto                        |
      | 54          | 77541694    | 30/10/2025  |                   | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario agregar un concepto                        |
      | 55          | 77541694    | 30/10/2025  |                   |                                 | NINGUNO  | 110     | sin gasto al credito       |         |        |          | sin_igv    | es necesario agregar un concepto                        |
      | 56          | 77541694    | 30/10/2025  |                   |                                 | NINGUNO  | 110     | sin gasto al credito       |         |        |          | sin_igv    | es necesario agregar un concepto                        |
      | 57          | 77541694    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 0       | gasto al credito rapido    |         |        |          | sin_igv    | es necesario agregar un concepto                        |
      | 58          | 77541694    | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 0       | gasto al credito rapido    |         |        |          | sin_igv    | es necesario agregar un concepto                        |
      | 59          | 77541694    | 30/10/2025  | Compra de insumos |                                 | NINGUNO  | 0       | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario agregar un concepto                        |
      | 60          | 77541694    | 30/10/2025  | Compra de insumos |                                 | NINGUNO  | 0       | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario agregar un concepto                        |
      | 61          | 77541694    | 30/10/2025  |                   | Compra de materiales de oficina | NINGUNO  | 0       | gasto al credito rapido    |         |        |          | sin_igv    | es necesario agregar un concepto                        |
      | 62          | 77541694    | 30/10/2025  |                   | Compra de materiales de oficina | NINGUNO  | 0       | gasto al credito rapido    |         |        |          | sin_igv    | es necesario agregar un concepto                        |
      | 63          | 77541694    | 30/10/2025  |                   |                                 | NINGUNO  | 0       | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario agregar un concepto                        |
      | 64          | 77541694    | 30/10/2025  |                   |                                 | NINGUNO  | 0       | gasto al credito configurable | 60      | 5      | 7        | sin_igv    | es necesario agregar un concepto                        |
      | 65          | 20172356720 | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito rapido    |         |        |          | con_igv    | es necesario agregar un concepto                        |
      | 66          | 20172356720 | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito rapido    |         |        |          | con_igv    | es necesario agregar un concepto                        |
      | 67          | 20172356720 | 30/10/2025  | Compra de insumos |                                 | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario agregar un concepto                        |
      | 68          | 20172356720 | 30/10/2025  | Compra de insumos |                                 | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario agregar un concepto                        |
      | 69          | 20172356720 | 30/10/2025  |                   | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario agregar un concepto                        |
      | 70          | 20172356720 | 30/10/2025  |                   | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario agregar un concepto                        |
      | 71          | 20172356720 | 30/10/2025  |                   |                                 | NINGUNO  | 110     | sin gasto al credito       |         |        |          | con_igv    | es necesario agregar un concepto                        |
      | 72          | 20172356720 | 30/10/2025  |                   |                                 | NINGUNO  | 110     | sin gasto al credito       |         |        |          | con_igv    | es necesario agregar un concepto                        |
      | 73          | 20172356720 | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 0       | gasto al credito rapido    |         |        |          | con_igv    | es necesario agregar un concepto                        |
      | 74          | 20172356720 | 30/10/2025  | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 0       | gasto al credito rapido    |         |        |          | con_igv    | es necesario agregar un concepto                        |
      | 75          | 20172356720 | 30/10/2025  | Compra de insumos |                                 | NINGUNO  | 0       | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario agregar un concepto                        |
      | 76          | 20172356720 | 30/10/2025  | Compra de insumos |                                 | NINGUNO  | 0       | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario agregar un concepto                        |
      | 77          | 20172356720 | 30/10/2025  |                   | Compra de materiales de oficina | NINGUNO  | 0       | gasto al credito rapido    |         |        |          | con_igv    | es necesario agregar un concepto                        |
      | 78          | 20172356720 | 30/10/2025  |                   | Compra de materiales de oficina | NINGUNO  | 0       | gasto al credito rapido    |         |        |          | con_igv    | es necesario agregar un concepto                        |
      | 79          | 20172356720 | 30/10/2025  |                   |                                 | NINGUNO  | 0       | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario agregar un concepto                        |
      | 80          | 20172356720 | 30/10/2025  |                   |                                 | NINGUNO  | 0       | gasto al credito configurable | 60      | 5      | 7        | con_igv    | es necesario agregar un concepto                        |
      | 81          | 20172356720 |             | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito rapido    |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 82          | 20172356720 |             | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito rapido    |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 83          | 20172356720 |             | Compra de insumos |                                 | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 84          | 20172356720 |             | Compra de insumos |                                 | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 85          | 20172356720 |             |                   | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito rapido    |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 86          | 20172356720 |             |                   | Compra de materiales de oficina | NINGUNO  | 110     | gasto al credito rapido    |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 87          | 20172356720 |             |                   |                                 | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 88          | 20172356720 |             |                   |                                 | NINGUNO  | 110     | gasto al credito configurable | 60      | 5      | 7        | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 89          | 20172356720 |             | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 0       | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 90          | 20172356720 |             | Compra de insumos | Compra de materiales de oficina | NINGUNO  | 0       | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 91          | 20172356720 |             | Compra de insumos |                                 | NINGUNO  | 0       | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 92          | 20172356720 |             | Compra de insumos |                                 | NINGUNO  | 0       | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 93          | 20172356720 |             |                   | Compra de materiales de oficina | NINGUNO  | 0       | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 94          | 20172356720 |             |                   | Compra de materiales de oficina | NINGUNO  | 0       | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 95          | 20172356720 |             |                   |                                 | NINGUNO  | 0       | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |
      | 96          | 20172356720 |             |                   |                                 | NINGUNO  | 0       | sin gasto al credito       |         |        |          | con_igv    | Es necesario ingresar la fecha de gasto                |