// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("GastosFeature")]
    public partial class GastosFeatureFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "GastosFeature", "  Como usuario del sistema\r\n  Quiero poder registrar gastos\r\n  Para gestionar los" +
                " gastos de la empresa", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "GastosFeature.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 9
#line hidden
#line 10
  await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://localhost:31096/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 11
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
  await testRunner.AndAsync("accede al módulo \'Gastos\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 13
  await testRunner.AndAsync("accede al submoudo \'Ver\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
  await testRunner.AndAsync("accede al submódulo \'NUEVO GASTO\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de nuevo gasto - Casos variados")]
        [NUnit.Framework.CategoryAttribute("RegistrarGasto")]
        [NUnit.Framework.TestCaseAttribute("1", "00000000", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "con_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("2", "00000000", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "con_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("3", "00000000", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("4", "00000000", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("5", "00000000", "30/10/2025", "", "Compra de materiales de oficina", "DESCUENTO", "0", "gasto al credito rapido", "", "", "", "con_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("6", "00000000", "30/10/2025", "", "Compra de materiales de oficina", "DESCUENTO", "0", "gasto al credito rapido", "", "", "", "con_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("7", "00000000", "30/10/2025", "", "", "DESCUENTO", "0", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("8", "00000000", "30/10/2025", "", "", "DESCUENTO", "0", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("9", "00000000", "", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("10", "00000000", "", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("11", "00000000", "", "Compra de insumos", "", "DESCUENTO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("12", "00000000", "", "Compra de insumos", "", "DESCUENTO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("13", "00000000", "", "", "Compra de materiales de oficina", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("14", "00000000", "", "", "Compra de materiales de oficina", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("15", "00000000", "", "", "", "DESCUENTO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("16", "00000000", "", "", "", "DESCUENTO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("17", "00000000", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("18", "00000000", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("19", "00000000", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("20", "00000000", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("21", "00000000", "30/10/2025", "", "Compra de materiales de oficina", "DESCUENTO", "0", "sin gasto al credito", "", "", "", "con_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("22", "00000000", "30/10/2025", "", "Compra de materiales de oficina", "DESCUENTO", "0", "sin gasto al credito", "", "", "", "con_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("23", "00000000", "30/10/2025", "", "", "DESCUENTO", "0", "sin gasto al credito", "", "", "", "con_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("24", "00000000", "30/10/2025", "", "", "DESCUENTO", "0", "sin gasto al credito", "", "", "", "con_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("25", "00000000", "", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("26", "00000000", "", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("27", "00000000", "", "Compra de insumos", "", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("28", "00000000", "", "Compra de insumos", "", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("29", "00000000", "", "", "Compra de materiales de oficina", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("30", "00000000", "", "", "Compra de materiales de oficina", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("31", "00000000", "", "", "", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("32", "00000000", "", "", "", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("33", "77541694", "30/10/2025", "", "", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "sin_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("34", "77541694", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "sin_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("35", "77541694", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "sin_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("36", "77541694", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "gasto al credito rapido", "", "", "", "sin_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("37", "77541694", "30/10/2025", "", "Compra de materiales de oficina", "DESCUENTO", "0", "gasto al credito rapido", "", "", "", "sin_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("38", "77541694", "30/10/2025", "", "Compra de materiales de oficina", "DESCUENTO", "0", "gasto al credito rapido", "", "", "", "sin_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("39", "77541694", "30/10/2025", "", "", "DESCUENTO", "0", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("40", "77541694", "30/10/2025", "", "", "DESCUENTO", "0", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("41", "77541694", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "gasto al credito configurable", "60", "5", "7", "sin_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("42", "77541694", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "DESCUENTO", "110", "gasto al credito configurable", "60", "5", "7", "sin_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("43", "77541694", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "sin_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("44", "77541694", "30/10/2025", "Compra de insumos", "", "DESCUENTO", "110", "sin gasto al credito", "", "", "", "sin_igv", "el gasto se registra exitosamente", null)]
        [NUnit.Framework.TestCaseAttribute("45", "77541694", "30/10/2025", "", "Compra de materiales de oficina", "DESCUENTO", "0", "sin gasto al credito", "", "", "", "sin_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("46", "77541694", "30/10/2025", "", "Compra de materiales de oficina", "DESCUENTO", "0", "sin gasto al credito", "", "", "", "sin_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("47", "77541694", "30/10/2025", "", "", "DESCUENTO", "0", "sin gasto al credito", "", "", "", "sin_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("48", "77541694", "30/10/2025", "", "", "DESCUENTO", "0", "sin gasto al credito", "", "", "", "sin_igv", "es necesario que el importe sea mayor a 0", null)]
        [NUnit.Framework.TestCaseAttribute("49", "77541694", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito rapido", "", "", "", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("50", "77541694", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito rapido", "", "", "", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("51", "77541694", "30/10/2025", "Compra de insumos", "", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("52", "77541694", "30/10/2025", "Compra de insumos", "", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("53", "77541694", "30/10/2025", "", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("54", "77541694", "30/10/2025", "", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("55", "77541694", "30/10/2025", "", "", "NINGUNO", "110", "sin gasto al credito", "", "", "", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("56", "77541694", "30/10/2025", "", "", "NINGUNO", "110", "sin gasto al credito", "", "", "", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("57", "77541694", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "0", "gasto al credito rapido", "", "", "", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("58", "77541694", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "0", "gasto al credito rapido", "", "", "", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("59", "77541694", "30/10/2025", "Compra de insumos", "", "NINGUNO", "0", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("60", "77541694", "30/10/2025", "Compra de insumos", "", "NINGUNO", "0", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("61", "77541694", "30/10/2025", "", "Compra de materiales de oficina", "NINGUNO", "0", "gasto al credito rapido", "", "", "", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("62", "77541694", "30/10/2025", "", "Compra de materiales de oficina", "NINGUNO", "0", "gasto al credito rapido", "", "", "", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("63", "77541694", "30/10/2025", "", "", "NINGUNO", "0", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("64", "77541694", "30/10/2025", "", "", "NINGUNO", "0", "gasto al credito configurable", "60", "5", "7", "sin_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("65", "20172356720", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito rapido", "", "", "", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("66", "20172356720", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito rapido", "", "", "", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("67", "20172356720", "30/10/2025", "Compra de insumos", "", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("68", "20172356720", "30/10/2025", "Compra de insumos", "", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("69", "20172356720", "30/10/2025", "", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("70", "20172356720", "30/10/2025", "", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("71", "20172356720", "30/10/2025", "", "", "NINGUNO", "110", "sin gasto al credito", "", "", "", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("72", "20172356720", "30/10/2025", "", "", "NINGUNO", "110", "sin gasto al credito", "", "", "", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("73", "20172356720", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "0", "gasto al credito rapido", "", "", "", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("74", "20172356720", "30/10/2025", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "0", "gasto al credito rapido", "", "", "", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("75", "20172356720", "30/10/2025", "Compra de insumos", "", "NINGUNO", "0", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("76", "20172356720", "30/10/2025", "Compra de insumos", "", "NINGUNO", "0", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("77", "20172356720", "30/10/2025", "", "Compra de materiales de oficina", "NINGUNO", "0", "gasto al credito rapido", "", "", "", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("78", "20172356720", "30/10/2025", "", "Compra de materiales de oficina", "NINGUNO", "0", "gasto al credito rapido", "", "", "", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("79", "20172356720", "30/10/2025", "", "", "NINGUNO", "0", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("80", "20172356720", "30/10/2025", "", "", "NINGUNO", "0", "gasto al credito configurable", "60", "5", "7", "con_igv", "es necesario agregar un concepto", null)]
        [NUnit.Framework.TestCaseAttribute("81", "20172356720", "", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito rapido", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("82", "20172356720", "", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito rapido", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("83", "20172356720", "", "Compra de insumos", "", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("84", "20172356720", "", "Compra de insumos", "", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("85", "20172356720", "", "", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito rapido", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("86", "20172356720", "", "", "Compra de materiales de oficina", "NINGUNO", "110", "gasto al credito rapido", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("87", "20172356720", "", "", "", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("88", "20172356720", "", "", "", "NINGUNO", "110", "gasto al credito configurable", "60", "5", "7", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("89", "20172356720", "", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "0", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("90", "20172356720", "", "Compra de insumos", "Compra de materiales de oficina", "NINGUNO", "0", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("91", "20172356720", "", "Compra de insumos", "", "NINGUNO", "0", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("92", "20172356720", "", "Compra de insumos", "", "NINGUNO", "0", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("93", "20172356720", "", "", "Compra de materiales de oficina", "NINGUNO", "0", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("94", "20172356720", "", "", "Compra de materiales de oficina", "NINGUNO", "0", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("95", "20172356720", "", "", "", "NINGUNO", "0", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        [NUnit.Framework.TestCaseAttribute("96", "20172356720", "", "", "", "NINGUNO", "0", "sin gasto al credito", "", "", "", "con_igv", "Es necesario ingresar la fecha de gasto", null)]
        public async System.Threading.Tasks.Task RegistroDeNuevoGasto_CasosVariados(string caso_Numero, string documento, string fecha_Gasto, string observaciones, string detalle, string concepto, string importe, string gasto_Al_Credito, string inicial, string cuotas, string dia_Pago, string manejo_Igv, string resultado_Esperado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegistrarGasto"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso_numero", caso_Numero);
            argumentsOfScenario.Add("documento", documento);
            argumentsOfScenario.Add("fecha_gasto", fecha_Gasto);
            argumentsOfScenario.Add("observaciones", observaciones);
            argumentsOfScenario.Add("detalle", detalle);
            argumentsOfScenario.Add("concepto", concepto);
            argumentsOfScenario.Add("importe", importe);
            argumentsOfScenario.Add("gasto_al_credito", gasto_Al_Credito);
            argumentsOfScenario.Add("inicial", inicial);
            argumentsOfScenario.Add("cuotas", cuotas);
            argumentsOfScenario.Add("dia_pago", dia_Pago);
            argumentsOfScenario.Add("manejo_igv", manejo_Igv);
            argumentsOfScenario.Add("resultado_esperado", resultado_Esperado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de nuevo gasto - Casos variados", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
await this.FeatureBackgroundAsync();
#line hidden
#line 18
  await testRunner.WhenAsync(string.Format("ingresa el documento \'{0}\'", documento), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
  await testRunner.AndAsync(string.Format("ingresa la fecha de gasto \'{0}\'", fecha_Gasto), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
  await testRunner.AndAsync(string.Format("ingresa observaciones \'{0}\'", observaciones), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
  await testRunner.AndAsync(string.Format("ingresa el detalle \'{0}\'", detalle), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 22
  await testRunner.AndAsync(string.Format("ingresa el concepto \'{0}\'", concepto), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
  await testRunner.AndAsync(string.Format("ingresa el importe \'{0}\'", importe), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
  await testRunner.AndAsync(string.Format("selecciona el tipo de gasto \'{0}\'", gasto_Al_Credito), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
  await testRunner.AndAsync(string.Format("para gastos al crédito configurable ingresa inicial \'{0}\' cuotas \'{1}\' y dia de p" +
                            "ago \'{2}\'", inicial, cuotas, dia_Pago), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
  await testRunner.AndAsync(string.Format("{0}", manejo_Igv), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
  await testRunner.ThenAsync(string.Format("{0}", resultado_Esperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
