// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AutomatizacionPOM.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("NewCotization")]
    public partial class NewCotizationFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "NewCotization", "  Como usuario del sistema\r\n  Quiero poder registrar cotizaciones\r\n  Para gestion" +
                "ar las cotizaciones de clientes", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "NewCotization.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
#line hidden
#line 8
  await testRunner.GivenAsync("el usuario ingresa al ambiente \'http://localhost:31096/\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 9
  await testRunner.WhenAsync("el usuario inicia sesión con usuario \'admin@plazafer.com\' y contraseña \'calidad\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
  await testRunner.AndAsync("accede al módulo \'Cotizacion\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
  await testRunner.AndAsync("accede al submódulo \'NUEVA COTIZACION\'", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Registro de nueva cotizacion - Casos variados")]
        [NUnit.Framework.CategoryAttribute("RegistrarCotizacion")]
        [NUnit.Framework.TestCaseAttribute("1", "1010-3", "2", "selecciona igv", "00000000", "01/12/2025", "la cotizacion se guarda correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("2", "400000437", "10", "selecciona igv", "77541694", "01/12/2025", "la cotizacion se guarda correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("3", "400000437", "10", "selecciona igv", "20172356720", "01/12/2025", "la cotizacion se guarda correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("4", "400000437", "10", "selecciona igv", "UNKNOWN", "01/12/2025", "la cotizacion se guarda correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("5", "400000437", "10", "no selecciona igv", "00000000", "01/12/2025", "la cotizacion se guarda correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("6", "400000437", "10", "no selecciona igv", "77541694", "01/12/2025", "la cotizacion se guarda correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("7", "400000437", "10", "no selecciona igv", "20172356720", "01/12/2025", "la cotizacion se guarda correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("8", "400000437", "10", "no selecciona igv", "UNKNOWN", "01/12/2025", "la cotizacion se guarda correctamente", null)]
        [NUnit.Framework.TestCaseAttribute("9", "400000437", "10", "selecciona igv", "00000000", "01/01/2020", "el sistema muestra mensaje de error", null)]
        [NUnit.Framework.TestCaseAttribute("10", "400000437", "10", "selecciona igv", "77541694", "01/01/2020", "el sistema muestra mensaje de error", null)]
        [NUnit.Framework.TestCaseAttribute("11", "400000437", "10", "selecciona igv", "20172356720", "01/01/2020", "el sistema muestra mensaje de error", null)]
        [NUnit.Framework.TestCaseAttribute("12", "400000437", "10", "selecciona igv", "Unknown", "01/01/2020", "el sistema muestra mensaje de error", null)]
        [NUnit.Framework.TestCaseAttribute("13", "400000437", "10", "no selecciona igv", "00000000", "01/01/2020", "el sistema muestra mensaje de error", null)]
        [NUnit.Framework.TestCaseAttribute("14", "400000437", "10", "no selecciona igv", "77541694", "01/01/2020", "el sistema muestra mensaje de error", null)]
        [NUnit.Framework.TestCaseAttribute("15", "400000437", "10", "no selecciona igv", "20172356720", "01/01/2020", "el sistema muestra mensaje de error", null)]
        [NUnit.Framework.TestCaseAttribute("16", "400000437", "10", "no selecciona igv", "Unknown", "01/01/2020", "el sistema muestra mensaje de error", null)]
        [NUnit.Framework.TestCaseAttribute("17", "400000437", "0", "selecciona igv", "00000000", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("18", "400000437", "0", "selecciona igv", "77541694", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("19", "400000437", "0", "selecciona igv", "20172356720", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("20", "400000437", "0", "selecciona igv", "Unknown", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("21", "400000437", "0", "no selecciona igv", "00000000", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("22", "400000437", "0", "no selecciona igv", "77541694", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("23", "400000437", "0", "no selecciona igv", "20172356720", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("24", "400000437", "0", "no selecciona igv", "Unknown", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("25", "400000437", "0", "selecciona igv", "00000000", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("26", "400000437", "0", "selecciona igv", "77541694", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("27", "400000437", "0", "selecciona igv", "20172356720", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("28", "400000437", "0", "selecciona igv", "Unknown", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("29", "400000437", "0", "no selecciona igv", "00000000", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("30", "400000437", "0", "no selecciona igv", "77541694", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("31", "400000437", "0", "no selecciona igv", "20172356720", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("32", "400000437", "0", "no selecciona igv", "Unknown", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("33", "ninguno", "10", "selecciona igv", "00000000", "01/12/2025", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("34", "ninguno", "10", "selecciona igv", "77541694", "01/12/2025", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("35", "ninguno", "10", "selecciona igv", "20172356720", "01/12/2025", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("36", "ninguno", "10", "selecciona igv", "Unknown", "01/12/2025", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("37", "ninguno", "10", "no selecciona igv", "00000000", "01/12/2025", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("38", "ninguno", "10", "no selecciona igv", "77541694", "01/12/2025", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("39", "ninguno", "10", "no selecciona igv", "20172356720", "01/12/2025", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("40", "ninguno", "10", "no selecciona igv", "Unknown", "01/12/2025", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("41", "ninguno", "10", "selecciona igv", "00000000", "01/01/2020", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("42", "ninguno", "10", "selecciona igv", "77541694", "01/01/2020", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("43", "ninguno", "10", "selecciona igv", "20172356720", "01/01/2020", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("44", "ninguno", "10", "selecciona igv", "Unknown", "01/01/2020", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("45", "ninguno", "10", "no selecciona igv", "00000000", "01/01/2020", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("46", "ninguno", "10", "no selecciona igv", "77541694", "01/01/2020", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("47", "ninguno", "10", "no selecciona igv", "20172356720", "01/01/2020", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("48", "ninguno", "10", "no selecciona igv", "Unknown", "01/01/2020", "el sistema muestra mensaje: \'Es necesario seleccionar al menos un producto\'", null)]
        [NUnit.Framework.TestCaseAttribute("49", "ninguno", "0", "selecciona igv", "00000000", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("50", "ninguno", "0", "selecciona igv", "77541694", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("51", "ninguno", "0", "selecciona igv", "20172356720", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("52", "ninguno", "0", "selecciona igv", "Unknown", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("53", "ninguno", "0", "no selecciona igv", "00000000", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("54", "ninguno", "0", "no selecciona igv", "77541694", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("55", "ninguno", "0", "no selecciona igv", "20172356720", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("56", "ninguno", "0", "no selecciona igv", "Unknown", "01/12/2025", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("57", "ninguno", "0", "selecciona igv", "00000000", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("58", "400000437", "0", "selecciona igv", "77541694", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("59", "ninguno", "0", "selecciona igv", "20172356720", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("60", "ninguno", "0", "selecciona igv", "Unknown", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("61", "ninguno", "0", "no selecciona igv", "00000000", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("62", "ninguno", "0", "no selecciona igv", "77541694", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("63", "ninguno", "0", "no selecciona igv", "20172356720", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        [NUnit.Framework.TestCaseAttribute("64", "ninguno", "0", "no selecciona igv", "Unknown", "01/01/2020", "el sistema muestra mensaje: \'Es necesario que el importe total sea mayor a 0.00\'", null)]
        public async System.Threading.Tasks.Task RegistroDeNuevaCotizacion_CasosVariados(string caso, string concepto, string cantidad, string selecciona_Igv, string documento, string fecha_Vencimiento, string resultado_Esperado, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "RegistrarCotizacion"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("caso", caso);
            argumentsOfScenario.Add("concepto", concepto);
            argumentsOfScenario.Add("cantidad", cantidad);
            argumentsOfScenario.Add("selecciona_igv", selecciona_Igv);
            argumentsOfScenario.Add("documento", documento);
            argumentsOfScenario.Add("fecha_vencimiento", fecha_Vencimiento);
            argumentsOfScenario.Add("resultado_esperado", resultado_Esperado);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Registro de nueva cotizacion - Casos variados", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
await this.FeatureBackgroundAsync();
#line hidden
#line 15
  await testRunner.WhenAsync(string.Format("el usuario agrega el concepto \'{0}\'", concepto), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
  await testRunner.AndAsync(string.Format("ingresa la cantidad \'{0}\'", cantidad), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
  await testRunner.AndAsync(string.Format("{0}", selecciona_Igv), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
  await testRunner.AndAsync(string.Format("selecciona al cliente con documento \'{0}\'", documento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
  await testRunner.AndAsync(string.Format("ingresa la fecha de vencimiento \'{0}\'", fecha_Vencimiento), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 20
  await testRunner.ThenAsync(string.Format("{0}", resultado_Esperado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
